### ISSUE TITLE
up to what version of MantisBT does gauge-support work ?

### ISSUE THREAD

**Issue by luzpaz** [EvilRenegade/Gauge-Support#1]

**Comment by EvilRenegade** [comment]
The honest answer is "I have no fucking clue".
We stopped actively using Mantis in favor of LaunchPad at version 1.2.5 in November 2011. Hence why there have been no updates to this code.

If Mantis's design is clean, I would expect the API to remain stable throughout the 1.2.x series, but beyond that, I really couldn't tell you.

**Comment by luzpaz** [comment]
Thanks for the answer. BTW, why did you jump ship ?

**Comment by EvilRenegade** [comment]
End users, mostly.
Mantis is very technical. LaunchPad has distilled (read: dumbed down) the whole process of reporting a bug into a few input fields, spread out over multiple pages, while scriptically holding the user's hand.

As a developer, I liked Mantis. It has fields for almost everything and is very flexible. But I spent a lot of time moderating and fixing up end users' tickets, because they couldn't handle the complexity.

I seriously went as far as adding a representation of MS Office's clippy to pop up when what they were entering couldn't possibly make sense, and added code to make the submit button jump around if they were about to submit bullshit.

Put bluntly: Mantis is a very nice tool for technicians, but our end users were no technicians.

Add to that that Mantis (at least back then) had some very interesting/questionable coding decisions and only ever seemed to gain new features when someone was desperate enough to code them (i.e. an itch-based development, rather than planned or product based development), and that its overall look and feel seemed a bit dated, and looking at other options became even easier.

I would still recommend Mantis as your tracker if your hosting is PHP-based and your users (or workflow) are compatible with it. 

It's sort of like an ended relationship...it's not that I stopped loving Mantis, it just didn't work out anymore. ;)

**Comment by luzpaz** [comment]
Wow, that was a very thoughtful and thorough answer which made me laugh. I appreciate the perspective. Especially because I'm used to github and more of the flashier types of BTs. I though that mantis was outdated. a relic still used by people set in their ways and not open to the UI changes of today. Your perspective offers the paradox of Mantis's situation, a sophisticated BT that is not keeping with the times and a tragic development paradigm. 

Also, hilariously tragic to think how desperate you were that you needed to invoke MS Clippy. Sorry to hear that man, [shoulder pat]. BTW, I also liked your analogy of an 'ended relationship' as well. Apropos. 

Cheers!

Edit: typos

**Comment by jetic83** [comment]
Thank you for this nice plugin! I added it to my mantis. But unfortunately, I cannot creat the gauge data.

in issue_ranking.php, the query

$dbquery = "SELECT
		max(sd.bugid) as bugid,
		count(sd.rating) as no_of_ratings,
		sum(sd.rating) as sum_of_ratings,
		avg(sd.rating) as avg_rating,
		max(sd.rating) as highest_rating,
		min(sd.rating) as lowest_rating,
		IFNULL(bm2_count,0) AS bm2_count,
		IFNULL(bm2_sum,0) AS bm2_sum,
		IFNULL(bm1_count,0) AS bm1_count,
		IFNULL(bm1_sum,0) AS bm1_sum,
		IFNULL(b2_count,0) AS b2_count,
		IFNULL(b2_sum,0) AS b2_sum,
		IFNULL(b1_count,0) AS b1_count,
		IFNULL(b1_sum,0) AS b1_sum
	FROM {$plugin_table} sd
	INNER JOIN {$bug_table} b ON sd.bugid = b.id
	LEFT OUTER JOIN (SELECT bugid, count(rating) as bm2_count, sum(rating) as bm2_sum FROM {$plugin_table} GROUP BY bugid, rating HAVING rating = -2) bm2 ON sd.bugid = bm2.bugid
	LEFT OUTER JOIN (SELECT bugid, count(rating) as bm1_count, sum(rating) as bm1_sum FROM {$plugin_table} GROUP BY bugid, rating HAVING rating = -1) bm1 ON sd.bugid = bm1.bugid
	LEFT OUTER JOIN (SELECT bugid, count(rating) as b2_count, sum(rating) as b2_sum FROM {$plugin_table} GROUP BY bugid, rating HAVING rating = 2) b2 ON sd.bugid = b2.bugid
	LEFT OUTER JOIN (SELECT bugid, count(rating) as b1_count, sum(rating) as b1_sum FROM {$plugin_table} GROUP BY bugid, rating HAVING rating = 1) b1 ON sd.bugid = b1.bugid
	{$where_clause}
	GROUP BY sd.bugid
	ORDER BY sum(sd.rating) {$order}
	LIMIT {$start}{$noOfBugs}";

results in the error "Database query failed. Error received from database was #1054: Unknown column 'rating' in 'having clause' for the query".

When I add the column "rating", I still get an other error. New query:

$dbquery = "SELECT
		max(sd.bugid) as bugid,
		count(sd.rating) as no_of_ratings,
		sum(sd.rating) as sum_of_ratings,
		avg(sd.rating) as avg_rating,
		max(sd.rating) as highest_rating,
		min(sd.rating) as lowest_rating,
		IFNULL(bm2_count,0) AS bm2_count,
		IFNULL(bm2_sum,0) AS bm2_sum,
		IFNULL(bm1_count,0) AS bm1_count,
		IFNULL(bm1_sum,0) AS bm1_sum,
		IFNULL(b2_count,0) AS b2_count,
		IFNULL(b2_sum,0) AS b2_sum,
		IFNULL(b1_count,0) AS b1_count,
		IFNULL(b1_sum,0) AS b1_sum
	FROM {$plugin_table} sd
	INNER JOIN {$bug_table} b ON sd.bugid = b.id
	LEFT OUTER JOIN (SELECT bugid, rating, count(rating) as bm2_count, sum(rating) as bm2_sum FROM {$plugin_table} GROUP BY bugid, rating HAVING rating = -2) bm2 ON sd.bugid = bm2.bugid
	LEFT OUTER JOIN (SELECT bugid, rating, count(rating) as bm1_count, sum(rating) as bm1_sum FROM {$plugin_table} GROUP BY bugid, rating HAVING rating = -1) bm1 ON sd.bugid = bm1.bugid
	LEFT OUTER JOIN (SELECT bugid, rating, count(rating) as b2_count, sum(rating) as b2_sum FROM {$plugin_table} GROUP BY bugid, rating HAVING rating = 2) b2 ON sd.bugid = b2.bugid
	LEFT OUTER JOIN (SELECT bugid, rating, count(rating) as b1_count, sum(rating) as b1_sum FROM {$plugin_table} GROUP BY bugid, rating HAVING rating = 1) b1 ON sd.bugid = b1.bugid
	{$where_clause}
	GROUP BY sd.bugid
	ORDER BY sum(sd.rating) {$order}
	LIMIT {$start}{$noOfBugs}";

New Error: "Database query failed. Error received from database was #1111: Invalid use of group function for the query"

Any suggestion?
